# Generated by Django 3.2.3 on 2021-07-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pMentHa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clareza', models.IntegerField()),
                ('pertinencia', models.IntegerField()),
                ('help', models.CharField(max_length=10)),
                ('original', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='stimulus',
            field=models.IntegerField(null=True),
        ),
    ]
